### ISSUE TITLE
Função do Pulo lógico para algumas perguntas.

### ISSUE THREAD

**Issue by kaardeco** [kaardeco/coviDiag-19#4]
Em algumas perguntas será necessário criar um pulo logico baseado na pergunta anterior.

**Comment by italosilva01** [comment]
Fiz a análise de quais questões deveriam ser pulada. Vi que era só a oitava questão que dependia da sétima resposta. Assim, Fiz um mecânismo de pular. No momento está específico para questão sete, mas com uns pequenos ajustes ela deve servir para outros casos.
